@baseURL = http://localhost:5000/api/v1/auth

### User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "name": "Imam",
    "email": "example@email.com",
    "password": "password"
}


### User Signin
POST {{ baseURL }}/signin
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}


### Google Signin
GET {{baseURL}}/google
