@base = http://localhost:5000
@baseURL = http://localhost:5000/api/v1

### Create Credential
POST {{ baseURL }}/credential/create
Content-Type: application/json

{
  "username": "example@email.com",
  "apikey": "demo-key"
}

### Update Credential
POST {{ baseURL }}/update
Content-Type: application/json

{
  "username": "example@email.com",
  "apikey": "demo-key"
}
